---
#To uninstall:
#`sudo ninja -Cbuild-auto uninstall`

- name: Uninstall Scrcpy
  ansible.builtin.shell: ninja -Cbuild-auto uninstall
  args:
    chdir: "{{ repo_dir }}"
    removes: /usr/local/share/scrcpy
  become: true